### ISSUE TITLE
NewsLetter

### ISSUE THREAD

**Issue by Shamimrahman** [TeamGladiators/HotelWeb#1]
Guest can sent message to admin via web.

**Comment by Shamimrahman** [comment]
guys idea deo kivabe korbo..? ami chaitesilam amra website page theke direct message admin er kase sent korte..

**Comment by Shamimrahman** [comment]
message.php file added.now newsletter and newsleeterdel add kora lagbe..message file theke follower o list chk kora jabe

**Comment by Shamimrahman** [comment]
contact sql file create in xampp mysql

**Comment by Ekramm** [comment]
Sending direct massage can be a good idea, but lets make it like, admin also can rply and  he can also make srvices for the customers

**Comment by BarshaDas** [comment]
Ai part tuku ami ready korechi..ekhn ki ami tahole code push kore dei
