### ISSUE TITLE
SettingPart

### ISSUE THREAD

**Issue by BarshaDas** [TeamGladiators/HotelWeb#3]
Ratul please push the setting part jetukui complete hoise

**Comment by Ekramm** [comment]
I added the code..room add delete function gulor code ta talbia kore dibe

**Comment by Talbia** [comment]
ami push kore dicchi

**Comment by Shamimrahman** [comment]
Single room er jonno ekta function create kore delei hbe ekhn

**Comment by Talbia** [comment]
Done this Part.
